name: crypto-exchange-monitor
services:
- name: monitor-service
  source_dir: .
  github:
    repo: Davis1233798/exchange_monitor
    branch: main
    deploy_on_push: true
  run_command: npm start
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 8080
  health_check:
    http_path: /health
    initial_delay_seconds: 60
    period_seconds: 30
    timeout_seconds: 10
    success_threshold: 1
    failure_threshold: 3
  routes:
  - path: /
  envs:
  - key: NODE_ENV
    value: production
  - key: PORT
    value: "8080"
  - key: BITGET_API_KEY
    scope: RUN_TIME
    type: SECRET
  - key: BITGET_SECRET_KEY
    scope: RUN_TIME
    type: SECRET
  - key: BITGET_PASSPHRASE
    scope: RUN_TIME
    type: SECRET
  - key: DISCORD_WEBHOOK_URL
    scope: RUN_TIME
    type: SECRET
  - key: TZ
    value: Asia/Taipei