version: '3.8'

services:
  crypto-exchange-monitor:
    image: crypto-exchange-monitor:latest
    container_name: crypto-exchange-monitor
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - TZ=Asia/Taipei
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./config:/app/config
    networks:
      - exchange-monitor-network
    healthcheck:
      test: ["CMD", "node", "-e", "console.log('Health check passed')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  # 可選：添加 Redis 用於快取和數據存儲
  redis:
    image: redis:7-alpine
    container_name: exchange-monitor-redis
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data
    networks:
      - exchange-monitor-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "2"

volumes:
  redis-data:
    driver: local

networks:
  exchange-monitor-network:
    driver: bridge