name: Manual Deploy (PM2) - DISABLED

on:
  # 暫時禁用此工作流程，改用 systemd 部署 (cd.yml)
  # workflow_dispatch:
  manual_trigger: # 禁用自動觸發
    inputs:
      environment:
        description: 'Deployment environment'
        required: true
        default: 'production'
        type: choice
        options:
        - production
        - staging
      restart_only:
        description: 'Only restart the service (skip code update)'
        required: false
        default: false
        type: boolean

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      if: ${{ !inputs.restart_only }}
      uses: actions/checkout@v4
      
    - name: Setup SSH key
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.GCP_SSH_PRIVATE_KEY }}
        
    - name: Deploy to GCP
      if: ${{ !inputs.restart_only }}
      run: |
        echo "🚀 Starting deployment to ${{ inputs.environment }}..."
        
        # 添加已知主機
        ssh-keyscan -H ${{ secrets.GCP_HOST || '35.212.185.14' }} >> ~/.ssh/known_hosts
        
        # 上傳代碼到服務器
        rsync -avz --delete \
          --exclude 'node_modules' \
          --exclude '.git' \
          --exclude '.env' \
          --exclude 'data/monitor.db' \
          ./ ${{ secrets.GCP_USER || 'JackChen6203' }}@${{ secrets.GCP_HOST || '35.212.185.14' }}:/home/JackChen6203/crypto-exchange-monitor/
        
        # 在服務器上執行部署命令
        ssh -o StrictHostKeyChecking=no ${{ secrets.GCP_USER || 'JackChen6203' }}@${{ secrets.GCP_HOST || '35.212.185.14' }} "
          cd /home/JackChen6203/crypto-exchange-monitor
          
          echo '📦 Installing dependencies...'
          npm install --only=production
          
          echo '⏹️ Stopping existing service...'
          pm2 stop crypto-monitor || echo 'No existing process to stop'
          
          echo '🚀 Starting service...'
          pm2 start src/index.js --name crypto-monitor --env ${{ inputs.environment }}
          pm2 save
          
          echo '✅ Deployment completed!'
          pm2 status crypto-monitor
        "
        
    - name: Restart service only
      if: ${{ inputs.restart_only }}
      run: |
        echo "🔄 Restarting service on ${{ inputs.environment }}..."
        
        ssh-keyscan -H ${{ secrets.GCP_HOST || '35.212.185.14' }} >> ~/.ssh/known_hosts
        
        ssh -o StrictHostKeyChecking=no ${{ secrets.GCP_USER || 'JackChen6203' }}@${{ secrets.GCP_HOST || '35.212.185.14' }} "
          echo '🔄 Restarting crypto-monitor service...'
          pm2 restart crypto-monitor || pm2 start src/index.js --name crypto-monitor --env ${{ inputs.environment }}
          pm2 save
          
          echo '✅ Service restarted!'
          pm2 status crypto-monitor
        "
        
    - name: Health check
      run: |
        echo "🏥 Performing health check..."
        sleep 10
        
        ssh -o StrictHostKeyChecking=no ${{ secrets.GCP_USER || 'JackChen6203' }}@${{ secrets.GCP_HOST || '35.212.185.14' }} "
          pm2 status crypto-monitor
          echo 'Service logs (last 10 lines):'
          pm2 logs crypto-monitor --lines 10 --nostream || echo 'No logs available'
        "
